name: validate

on: # Rebuild any PRs and main branch changes
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.tool-versions'
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn lint
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.tool-versions'
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn format
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.tool-versions'
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn test
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v5
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.tool-versions'
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn build
